version: "3.9"

services:
  redis:
    image: redis

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
  
  cable:
    build: .
    command: bundle exec puma -p 28080 cable/config.ru
    depends_on:
      - db
      - web
